name: HubSpot DLT Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: hubspot-pipeline
  cancel-in-progress: true

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
#    env:
#      HUBSPOT__SOURCES__HUBSPOT__API_KEY: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
#      DESTINATION__SNOWFLAKE__ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#      DESTINATION__SNOWFLAKE__USER: PARHAMBRZ120
#      DESTINATION__SNOWFLAKE__PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
#      DESTINATION__SNOWFLAKE__ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
#      DESTINATION__SNOWFLAKE__WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
#      DESTINATION__SNOWFLAKE__DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
#      DESTINATION__SNOWFLAKE__SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Check secrets
        run: |
          echo "SNOWFLAKE_USER secret exists? ${#SNOWFLAKE_USER} chars"
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}

      - name: Prepare DLT secrets
        run: |
          mkdir -p ~/.dlt

          cat > ~/.dlt/secrets.toml <<'EOF'
          [sources.hubspot]
          api_key = "${{ secrets.HUBSPOT_ACCESS_TOKEN }}"

          [destination.snowflake.credentials]
          username = "${{ vars.SNOWFLAKE_USERNAME }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          host = "${{ vars.SNOWFLAKE_HOST }}"
          database = "${{ vars.SNOWFLAKE_DATABASE }}"
          warehouse = "${{ vars.SNOWFLAKE_WAREHOUSE }}"
          role = "${{ vars.SNOWFLAKE_ROLE }}"
          EOF
        env:
          SNOWFLAKE_WAREHOUSE: TEST

      - name: Check secrets.toml exists
        run: |
          ls -l ~/.dlt
          head -n 15 ~/.dlt/secrets.toml

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run HubSpot pipeline
        run: python -u hubspot_pipeline.py
